SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS PurchaseEntry CASCADE;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE PurchaseEntry
(
  id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  purchaseName VARCHAR(30) NOT NULL,
  date DATE NOT NULL,
  amount DOUBLE(10,2) NOT NULL,
  metadata VARCHAR(30) NOT NULL
);